from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Literal, Dict

# ---------------------------------------------------------
# 1. FORENSIC REASONING SCHEMAS (AI OUTPUT MAPPING)
# ---------------------------------------------------------

class ReasoningTree(BaseModel):
    """Deep-dive explanation generated by the AI for complex bias vectors."""
    type: str = Field(..., description="Classification of the bias (e.g., 'Systemic Exclusion', 'Linguistic Affinity')")
    cause: str = Field(..., description="The structural, historical, or systemic root cause.")
    impact: str = Field(..., description="The predicted downstream impact on marginalized demographics.")

class Finding(BaseModel):
    """Individual bias incident mapping. Powers the UI Semantic Heatmap."""
    quote: str = Field(..., description="The exact biased phrase extracted from the text.")
    
    # Optional offsets for dynamic frontend highlighting
    startIndex: Optional[int] = Field(None, description="Starting character index in the raw payload.")
    endIndex: Optional[int] = Field(None, description="Ending character index in the raw payload.")
    
    category: str = Field(..., description="The domain of bias (e.g., Gender, Racial, Age, Socioeconomic).")
    severity: Literal["low", "medium", "high", "critical"] = Field(..., description="Calculated systemic risk level.")
    
    is_proxy: bool = Field(default=False, description="True if the term is a latent proxy variable (e.g., 'zip code' masking race).")
    
    # Unified XAI (Explainable AI) properties
    proof: str = Field(..., description="Direct Ratiocination/Explainable AI reasoning for the flag.")
    reasoning_tree: Optional[ReasoningTree] = Field(None, description="Expanded logical breakdown for high-severity flags.")
    
    recommendation: str = Field(..., description="Suggested neutral, inclusive replacement to neutralize the vector.")
    policy_improvement: Optional[str] = Field(None, description="Broader ethical policy correction for the institution.")
    sdg: Optional[str] = Field(None, description="Relevant UN Sustainable Development Goal mapping (e.g., 'SDG 10.3').")

# ---------------------------------------------------------
# 2. REQUEST SCHEMAS (API PAYLOADS)
# ---------------------------------------------------------

class TextAuditRequest(BaseModel):
    """Payload for the primary text scanning engine."""
    text: str = Field(
        ..., 
        min_length=15, 
        max_length=25000, 
        description="The raw institutional intelligence source to analyze."
    )
    locale: str = Field(
        default="en-US", 
        description="Target locale context for cultural bias detection."
    )
    domain: str = Field(
        default="general", 
        description="Industry domain to adjust severity thresholds."
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "text": "We are looking for an aggressive salesman to join our fraternity of rockstars. Must live in an urban zip code.",
                "locale": "en-US",
                "domain": "hiring"
            }
        }
    )

class SimulationRequest(BaseModel):
    """Payload for the intersectional counterfactual simulator."""
    text: str = Field(..., min_length=10, max_length=15000, description="The original text to perturb.")
    variables_to_flip: List[str] = Field(
        ..., 
        min_length=1,
        description="Protected variables to dynamically alter (e.g., ['Gender', 'Name', 'Education'])."
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "text": "The candidate, John, brings an aggressive, fast-paced leadership style to the engineering team.",
                "variables_to_flip": ["Gender", "Name"]
            }
        }
    )

# ---------------------------------------------------------
# 3. RESPONSE SCHEMAS (API RETURNS)
# ---------------------------------------------------------

class ForensicResponse(BaseModel):
    """The master response object returned to the Next.js Text Forensics frontend."""
    overall_fairness_score: int = Field(..., ge=0, le=100, description="System-wide institutional parity index (0-100).")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="AI mathematical certainty percentage (0.0 to 1.0).")
    execution_time_seconds: Optional[float] = Field(None, description="API latency metric for backend telemetry.")
    target_locale: Optional[str] = Field(None, description="The locale used during the analysis.")
    findings: List[Finding] = Field(default_factory=list, description="Array of specific detected bias vectors.")

class SimulationResponse(BaseModel):
    """Response object for counterfactual Sandbox simulations."""
    simulated_text: str = Field(..., description="The counterfactual rewritten text with inverted demographics.")
    applied_changes: List[str] = Field(default_factory=list, description="Specific semantic changes executed by the LLM.")

class DatasetAuditMetadata(BaseModel):
    """Sub-model for dataset statistics."""
    total_records: int = Field(..., description="Total rows parsed.")
    protected_attribute: str = Field(..., description="The column audited.")
    privileged_class: Optional[str] = Field(None, description="The class acting as baseline.")
    decision_column: Optional[str] = Field(None, description="The target variable column.")

class DatasetAuditResponse(BaseModel):
    """Response object for mathematical CSV dataset auditing."""
    disparate_impact_ratio: float = Field(..., description="The exact mathematical DIR score.")
    status: Literal["Fair", "Biased", "Critical Bias"] = Field(..., description="Algorithmic pass/fail classification.")
    message: str = Field(..., description="Forensic explanation of the mathematical parity threshold.")
    metadata: DatasetAuditMetadata